CREATE TABLE ma_t_sys_languages (
    lang_code CHAR(2 CHAR),
    lang_desc VARCHAR2(50 CHAR),
    CONSTRAINT ma_pk_lang PRIMARY KEY (lang_code)    
);

CREATE TABLE ma_t_sys_currencies (
    curr_code CHAR(3 CHAR) NOT NULL,
    CONSTRAINT ma_pk_curr_code PRIMARY KEY (curr_code)
);

CREATE TABLE ma_t_sys_public_files (
    file_id      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_content BLOB,
    CONSTRAINT ma_pk_file_id PRIMARY KEY (file_id)    
);

CREATE TABLE ma_t_sys_server_logs (
    session_id    NUMBER(16),
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    ip            VARCHAR2(30 CHAR),
    agent         VARCHAR2(150 CHAR),
    CONSTRAINT ma_pk_session_id PRIMARY KEY (session_id)
);

CREATE TABLE ma_t_dict_currencies (
    curr_code CHAR(3 CHAR) NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    curr_name VARCHAR2(30 CHAR),
    CONSTRAINT ma_fk_curr_code FOREIGN KEY (curr_code) REFERENCES ma_t_sys_currencies(curr_code),
    CONSTRAINT ma_fk_lang_code_curr FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_trans_type (
    type_code CHAR(1 CHAR) NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    type_name VARCHAR2(50 CHAR),
    CONSTRAINT ma_fk_lang_code_trans_type FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_user_status (
    status_code CHAR(1 CHAR) NOT NULL,
    lang_code   CHAR(2 CHAR) NOT NULL,
    status_name VARCHAR2(30 CHAR),
    CONSTRAINT ma_fk_lang_code_user_status FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_penitentiary_unit (
    unit_code NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    unit_name VARCHAR2(250 CHAR),
    CONSTRAINT ma_pk_unit_code PRIMARY KEY (unit_code),
    CONSTRAINT ma_fk_lang_unit FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_regions (
    region_code NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lang_code   CHAR(2 CHAR) NOT NULL,
    region_name VARCHAR2(100 CHAR),
    CONSTRAINT ma_pk_region_code PRIMARY KEY (region_code),
    CONSTRAINT ma_fk_lang_region FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_users (
    user_id       NUMBER(6) DEFAULT ma_s_users.NEXTVAL,
    key           CHAR(6 CHAR),
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    lang_code     CHAR(2 CHAR) NOT NULL,
    it_is_paid    CHAR(1) DEFAULT 'y' NOT NULL,
    pin           CHAR(4) NOT NULL,
    name_user     VARCHAR2(250 CHAR),
    desc_user     CLOB,
    user_status   CHAR(1) DEFAULT 'c' NOT NULL,
    region_code   NUMBER(2) NOT NULL,
    avatar        BLOB,
    CONSTRAINT ma_pk_user_id PRIMARY KEY (user_id),
    CONSTRAINT ma_uq_key UNIQUE (key),
    CONSTRAINT ma_fk_lang_code_user FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code),
    CONSTRAINT ma_chk_it_is_paid CHECK (it_is_paid IN ('y', 'n')),
    CONSTRAINT ma_chk_user_status CHECK (user_status IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')),
    CONSTRAINT ma_fk_region_code FOREIGN KEY (region_code) REFERENCES ma_t_dict_regions(region_code)
);

CREATE TABLE ma_t_imprisonment (
    user_id       NUMBER(6) NOT NULL,
    unit_code     NUMBER(2) NOT NULL,
    prisoner_from DATE NOT NULL,
    prisoner_to   DATE NOT NULL,
    CONSTRAINT ma_fk_user_id_imprison FOREIGN KEY (user_id) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_uq_user_id_imprison UNIQUE (user_id),
    CONSTRAINT ma_fk_unit_code_imprison FOREIGN KEY (unit_code) REFERENCES ma_t_dict_penitentiary_unit(unit_code)
);

CREATE TABLE ma_t_recommendations (
    user_id_for   NUMBER(6) NOT NULL,
    user_id_who   NUMBER(6) NOT NULL,
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    comm          VARCHAR2(2000 CHAR),
    CONSTRAINT ma_fk_reco_user_id_for FOREIGN KEY (user_id_for) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_fk_reco_user_id_who FOREIGN KEY (user_id_who) REFERENCES ma_t_users(user_id)
);

CREATE TABLE ma_t_promo_visits (
    user_id       NUMBER(6) NOT NULL,
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    ip            VARCHAR2(30 CHAR),
    agent         VARCHAR2(150 CHAR),
    fbclid        VARCHAR2(200 CHAR),
    CONSTRAINT ma_fk_user_id_visits FOREIGN KEY (user_id) REFERENCES ma_t_users(user_id)
);

CREATE TABLE ma_t_promo_recruits (
    user_id_for   NUMBER(6) NOT NULL,
    user_id_who   NUMBER(6) NOT NULL,
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ma_fk_user_id_for FOREIGN KEY (user_id_for) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_fk_user_id_who FOREIGN KEY (user_id_who) REFERENCES ma_t_users(user_id)
);

CREATE TABLE ma_t_user_logs (
    session_id NUMBER(16) NOT NULL,
    user_id    NUMBER(6) NOT NULL,
    login_type CHAR(1) DEFAULT 'y' NOT NULL,
    CONSTRAINT ma_fk_session_id FOREIGN KEY (session_id) REFERENCES ma_t_sys_server_logs(session_id),
    CONSTRAINT ma_fk_user_id_logs FOREIGN KEY (user_id) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_chk_login_type CHECK (login_type IN ('y', 'n'))
);

CREATE TABLE ma_t_rooms (
    room_id   NUMBER(6) DEFAULT ma_s_rooms.NEXTVAL,
    room_name VARCHAR2(250 CHAR),
    desc_room CLOB,
    CONSTRAINT ma_pk_room_id PRIMARY KEY (room_id)
);

CREATE TABLE ma_t_guests_room (
    room_id   NUMBER(6) NOT NULL,
    user_id   NUMBER(6) NOT NULL,
    it_is_mod CHAR(1) DEFAULT 'n' NOT NULL,
    CONSTRAINT ma_fk_room_id_guests FOREIGN KEY (room_id) REFERENCES ma_t_rooms(room_id),
    CONSTRAINT ma_fk_user_id_guests FOREIGN KEY (user_id) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_chk_it_is_mod CHECK (it_is_mod IN ('y', 'n'))
);

CREATE TABLE ma_t_posts (
    post_id       NUMBER(10) DEFAULT ma_s_posts.NEXTVAL,
    room_id       NUMBER(6) NOT NULL,
    user_id       NUMBER(6) NOT NULL,
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    post_type     CHAR(1 CHAR) DEFAULT 'm' NOT NULL,
    CONSTRAINT ma_pk_post_id PRIMARY KEY (post_id),    
    CONSTRAINT ma_fk_room_id_posts FOREIGN KEY (room_id) REFERENCES ma_t_rooms(room_id),
    CONSTRAINT ma_fk_user_id_posts FOREIGN KEY (user_id) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_chk_post_type CHECK (post_type IN ('v', 'm', 'p', 'd', 'l'))
);

CREATE TABLE ma_t_messages (
    post_id NUMBER(6) NOT NULL,
    message CLOB,
    CONSTRAINT ma_fk_posts_messages FOREIGN KEY (post_id) REFERENCES ma_t_posts(post_id),
    CONSTRAINT ma_uq_posts_messages UNIQUE (post_id)
);

CREATE TABLE ma_t_pictures (
    post_id NUMBER(6) NOT NULL,
    picture BLOB,
    CONSTRAINT ma_fk_posts_pictures FOREIGN KEY (post_id) REFERENCES ma_t_posts(post_id),
    CONSTRAINT ma_uq_posts_pictures UNIQUE (post_id)
);

CREATE TABLE ma_t_documents (
    post_id  NUMBER(6) NOT NULL,
    document BLOB,
    CONSTRAINT ma_fk_posts_documents FOREIGN KEY (post_id) REFERENCES ma_t_posts(post_id),
    CONSTRAINT ma_uq_posts_documents UNIQUE (post_id)
);

CREATE TABLE ma_t_locations (
    post_id  NUMBER(6) NOT NULL,
    location MDSYS.SDO_GEOMETRY,
    CONSTRAINT ma_fk_posts_locations FOREIGN KEY (post_id) REFERENCES ma_t_posts(post_id),
    CONSTRAINT ma_uq_posts_locations UNIQUE (post_id)
);

CREATE TABLE ma_t_transactions (
    operation_id   NUMBER(10) DEFAULT ma_s_trans.NEXTVAL,
    user_id_to     NUMBER(6) NOT NULL,
    user_id_from   NUMBER(6) NOT NULL,
    date_creation  DATE DEFAULT SYSDATE NOT NULL,
    curr_code      CHAR(3 CHAR) NOT NULL,
    operation_type CHAR(1) DEFAULT 'a' NOT NULL,
    amount         NUMBER(7, 2) NOT NULL,
    title          VARCHAR2(2000 CHAR),
    CONSTRAINT ma_pk_operation_id PRIMARY KEY (operation_id),
    CONSTRAINT ma_fk_user_id_to FOREIGN KEY (user_id_to) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_fk_user_id_from FOREIGN KEY (user_id_from) REFERENCES ma_t_users(user_id),
    CONSTRAINT ma_fk_curr_code_trans FOREIGN KEY (curr_code) REFERENCES ma_t_sys_currencies(curr_code),
    CONSTRAINT ma_chk_operation_type CHECK (operation_type IN ('a', 'b', 'c', 'd', 'e', 'f'))
);