CREATE TABLE ma_t_sys_languages (
    lang_code CHAR(2 CHAR) NOT NULL,
    lang_desc VARCHAR2(50 CHAR),
    CONSTRAINT ma_pk_lang PRIMARY KEY (lang)    
);

CREATE TABLE ma_t_sys_server_logs (
    session_id NUMBER(16) NOT NULL,
    date_creation DATE DEFAULT SYSDATE NOT NULL,
    ip VARCHAR2(30 CHAR),
    agent VARCHAR2(150 CHAR),
    CONSTRAINT ma_pk_session_id PRIMARY KEY (session_id)
);

CREATE TABLE ma_t_currencies (
    curr_code CHAR(3 CHAR) NOT NULL,
    CONSTRAINT ma_pk_curr_code PRIMARY KEY (curr_code)
);

CREATE TABLE ma_t_trans_type (
    type_code CHAR(1 CHAR) NOT NULL,
    CONSTRAINT ma_pk_type_code PRIMARY KEY (type_code)
);

CREATE TABLE ma_t_user_status (
    status_code CHAR(1 CHAR) NOT NULL,
    CONSTRAINT ma_pk_status_code PRIMARY KEY (status_code)
);

CREATE TABLE ma_t_dict_currencies (
    curr_code CHAR(3 CHAR) NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    curr_name VHARCHAR2(30 CHAR),
    CONSTRAINT ma_fk_curr_code FOREIGN KEY (curr_code) REFERENCES ma_t_currencies(curr_code),
    CONSTRAINT ma_fk_lang_code_curr FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_trans_type (
    type_code CHAR(1 CHAR) NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    type_name VHARCHAR2(50 CHAR),
    CONSTRAINT ma_fk_type_code FOREIGN KEY (type_code) REFERENCES ma_t_trans_type(type_code),
    CONSTRAINT ma_fk_lang_code_trans_type FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_user_status (
    status_code CHAR(1 CHAR) NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    status_name VARCHAR2(30 CHAR),
    CONSTRAINT ma_fk_status_code FOREIGN KEY (status_code) REFERENCES ma_t_user_status(status_code),
    CONSTRAINT ma_fk_lang_code_user_status FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_penitentiary_unit (
    unit_code NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    unit_name VARCHAR2(250 CHAR),
    CONSTRAINT ma_pk_unit_code PRIMARY KEY (unit_code),
    CONSTRAINT ma_fk_lang_unit FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);

CREATE TABLE ma_t_dict_regions (
    region_code NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lang_code CHAR(2 CHAR) NOT NULL,
    region_name VARCHAR2(100 CHAR),
    CONSTRAINT ma_pk_region_code PRIMARY KEY (region_code),
    CONSTRAINT ma_fk_lang_region FOREIGN KEY (lang_code) REFERENCES ma_t_sys_languages(lang_code)
);